### PR TITLE
Simplify the unittests

### PR DESCRIPTION
**Pull request by kenrap**
<strike>This is something I've been pondering for a while now and now with my latest changes, it makes more sense to have the state numbers be 0-based instead of 1-based for indexing them.

This is subjective of course. In my opinion, this reads better and flows better.

It's your choice though.</strike>

### CODE REVIEW

**Comment by kenrap** [comment]
<strike>Btw, if this kind of change is not acceptable, allow me to force push a similar cleanup of the unittests following the 1-based.</strike>

**Comment by kenrap** [comment]
I realized this PR was too opinionated and not a valid contribution, therefore closing it.

Sorry about that and I hope you're doing all good! 😎

**Comment by YiJeongseop** [comment]
I'm so sorry. I just checked. I haven't used a computer recently.

I think it's really good to change 1-based to 0-based, too!

And, Thank you so much for changing test code! It looks better. 👍

**Comment by kenrap** [comment]
I'm glad to hear from you! I was overly concerned. No worries and thanks for getting back with me! 😁

**Comment by YiJeongseop** [comment]
You're welcome! I'm always grateful to you. 😆

**Pull request merged**
