### PR TITLE
Block turn method refactor completion

### PR DESCRIPTION
**Pull request by kenrap**
What I've learned from doing this is that using regex is not only a productivity feature (such when using it in *Vim) but one that prevents human prone errors when using the right regex patterns to match for the substitution of repeated code patterns.

If you haven't learned how to use Regular Expression, I _highly_ recommend doing so. And use them in your text editor of choice.

### CODE REVIEW

**Comment by YiJeongseop** [comment]
Regular Expression was one of the most difficult things when learning Python.. 😢 

Honestly, I didn't know well where it was used..

Thank you for letting me know!!

**Comment by kenrap** [comment]
Regex is great for when you noticed something about line(s) of code that are tedious to edit by hand and you're trying to extract pieces of text from those lines by matching for that pattern of text.

Unfortunately, regex doesn't really have a "standard" and different implementations of them can vary slightly, but all of them share a same common syntax for the most part, like 95% percent of it.

I used to not like regex in the past because of it's hard-to-follow syntax and concepts while not understanding how to really use it. That's why I bring this up.

The best way to learn it is by finding practical use for it, like in large codebases.

You can also use this site to play around and see how the regex matching works when it highlights the matched text in a user-friendly and visual learning way: https://regex101.com/

**Comment by kenrap** [comment]
I'll share an example of what I did in terms of collecting the `self.turnable_check_coords` list data from the `BlockT.turn` method. Within the `if self.tetris.state == 1:` statement block of code, I copied the following text outside the method.

```python
for x in range(3):
    if background_blocks[self.tetris.current_y_list[1] + 1][self.tetris.current_x_list[1] + x].not_block:
        return
if background_blocks[self.tetris.current_y_list[0]][self.tetris.current_x_list[1]].not_block:
    return
if background_blocks[self.tetris.current_y_list[0]][self.tetris.current_x_list[3]].not_block:
    return
```

I do a quick edit removing the `return` lines and unindent the first line once. This was easy for me to do in Vim.

```python
if background_blocks[self.tetris.current_y_list[1] + 1][self.tetris.current_x_list[1] + x].not_block:
if background_blocks[self.tetris.current_y_list[0]][self.tetris.current_x_list[1]].not_block:
if background_blocks[self.tetris.current_y_list[0]][self.tetris.current_x_list[3]].not_block:
```

Then I use this Vim regex substitution to convert those 3 lines. Please note that you can use delimiters other than `/`. I like using `:` instead because it's easier for me to read, but it means you have to escape for colons if you want to match them too.

```
s:\S.*\[\(\d\)\].*\[\(\d\)\].*:(\1, \2):
```
or to simplify this expression without escaping the parens/bracket:
```
s:\S.*[(\d)].*[(\d)].*:(\1, \2):
```
This is a bit complicated to explain but essentially I matched the numbers indexed for the y and x current lists as "groups" and then use the `\1` and `\2` back references from those groups to write something new, like the following:
```python
(1, 1),
(0, 1),
(0, 3),
```
This helped me to get the first list item of coords to add to `self.turnable_check_coords`, instantaneously!
It was just a matter of joining those lines and remove the comma at the end to produce the following.
```python
(1, 1), (0, 1), (0, 3)
```
And use this expression to finish it by wrapping brackets to make it an actual Python list expression with: `s:(.*):[&],:`.
The `&` means anything that was matched (while not using groups at all), use that as the back reference, similar to the `\1` stuff.
```python
[(1, 1), (0, 1), (0, 3)],
```
And there you have it, I've completed the turnable coords for the first turning state.

Lather-rinse-repeat for the same kind of code in states `2`, `3`, and `4`, in there respective if statement blocks. Huge time savings while being less error prone!

Btw, I'm able to reuse the same expressions again without typing them out again using the command history in Vim. These patterns are reusable, hence why it's fast to do this work.

**Comment by YiJeongseop** [comment]
Thanks for the detail!! 😄 

I'm still trying to understand, and I think the mix of different characters makes it harder to understand.

But this will greatly help me understand. Thank you so much again!

**Comment by kenrap** [comment]
I totally understand where you are coming from! And I sort felt like was too imposing with that detail earlier.

I wish there was some way I can help with "teaching" this somehow.

**Pull request merged**
